[tox]
envlist =
    py{313,314}
    py{313,314}-{fastvalidation,fastdateparsing,fastuuid,all}

[gh-actions]
python =
    3.13: py313
    3.14: py314

; To list all created environments + installation extras and more: `tox -l --showconfig`
[testenv]
commands =
    pytest tests
    black --check dataclasses_jsonschema tests setup.py
    isort --check-only dataclasses_jsonschema tests setup.py
    flake8 dataclasses_jsonschema
    mypy dataclasses_jsonschema
extras =
    test
    fastvalidation: fast-validation
    fastdateparsing: fast-dateparsing
    fastuuid: fast-uuid
    all: fast-validation, fast-dateparsing, fast-uuid
